/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomButton: typeof import('./src/components/customButton.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    ZineFront: typeof import('./src/components/zineFront.vue')['default']
  }
}
